CREATE TABLE IF NOT EXISTS STUDENT (
 ROLL_NO TEXT PRIMARY KEY,

 NAME TEXT NOT NULL,

 ADDRESS TEXT,

 PHONE TEXT,

 AGE INTEGER
);

INSERT INTO STUDENT(ROLL_NO, NAME, ADDRESS, PHONE, AGE) VALUES
('100', 'RAM', 'DELHI', '987654321', 18),

('200', 'SMITH', 'NEW YORK', '012345678', 19),

('300', 'RAJ', 'KATHMANDU', '987654321', 20);

SELECT * FROM STUDENT WHERE AGE=19 AND NAME="SMITH";

SELECT * FROM STUDENT WHERE AGE=19 OR NAME="RAJ";

SELECT MIN(AGE) FROM STUDENT;

SELECT MAX(ROLL_NO) FROM STUDENT;


